### ISSUE TITLE
Bad translation

### ISSUE THREAD

**Issue by thomasgodart** [dupoxy/go-tour-fr#30] opened 2018-05-23 17:09 UTC
Context: https://go-tour-fr.appspot.com/moretypes/14

In English "drop the" should translate in this context to "supprimez la partie", and not to "déposez la" as it is translated right now.

Thanks

**Comment by dupoxy** [comment] 2020-04-15 10:57
duplicate of #24

**Closed by dupoxy** 2020-04-15 10:57 UTC
